name: Push/PR

on:
  push:
    branches:
      - master
      - main
      - renovate/**
  pull_request:

jobs:
  push-pr:
    uses: newrelic/coreint-automation/.github/workflows/reusable_push_pr.yaml@v3
    secrets: inherit
    with:
      integration: "elasticsearch"
